### ISSUE TITLE
rename repository to `laxar-html-display-widget`

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-html-display-widget#16]
We would like to align artifact name and repository name to avoid confusion.

These points need to be checked (there may be more), after the GitHub repo has been renamed:

- [x] spec test: `describe( 'An ax...',` ...
- [x] file names: spec, HTML, SCSS/CSS
- [x] `package.json` fields: name repository.url; bugs.url; main; 
- [x] `README.md`: headline, links (use https://laxarjs.org/docs)
- [x] `CHANGELOG.md`: links

Note that this is no breaking change since the external artifact name (npm) is not affected.

**Comment by alex3683** [comment]
Fixed on `master` (`v3.0.0`).
